### PR TITLE
Allow use of legacy filenames

### PR DESCRIPTION
**Pull request by awilkins**
Allow the use of filenames from legacy version switchers for the golang plugin.

e.g. the Terraform source, which has a `.go-version` file in the root.

### CODE REVIEW

**Comment by kennyp** [comment]
@awilkins Looking at the docs it appears the legacy file support would come via `bin/list-legacy-filenames` and `bin/parse-legacy-file`. Where does `bin/get-version-from-legacy-file` get used?

For reference, I'm looking at https://asdf-vm.com/#/plugins-create?id=binlist-legacy-filenames

**Comment by awilkins** [comment]
I copied my implementation for another language, which I believe I implemented on the back of reading the source code, or copying another implementation.

The core might have moved on it how it does things.

**Comment by jacobbednarz** [comment]
+1 on support for this one. @awilkins @kennyp is anyone working on this one? If not I'm happy to push it forward.

**Comment by kennyp** [comment]
@jacobbednarz I haven't revisited yet, no. Based on the docs it should be as simple as adding a script called `bin/list-legacy-filenames` with something like:

```bash
#!/usr/bin/env bash

echo -n ".go-version"
```

@awilkins I would be glad for you to accept the PR if you want to switch to `bin/list-legacy-filenames`, or if not feel free to post one @jacobbednarz

**Comment by awilkins** [comment]
Having read the docs, the default implementation once you have the filename is to just `cat` it, so I've removed the script (some doubt as to whether it was even being called, possibly...)

Still works fine!

**Comment by kennyp** [comment]
Nice! Thanks.

**Pull request merged**
