### PR TITLE
Add tests for `parse-legacy-file`, to ensure the right version is selected

### PR DESCRIPTION
**Pull request by whi-tw**
Add tests for parsing `go.mod` and `.go-version`.

I considered replacing:

https://github.com/kennyp/asdf-golang/blob/f006a12d6e0c213dcfef8ee167eb0d2872b02055/bin/parse-legacy-file#L17

With `plugin_installs_path="${PLUGIN_INSTALLS_PATH:-$(install_dir)}"` and passing in a path with preexisting dummy install directories, but wanted to make sure it was an e2e test of the whole function, so creating directories in a correctly relative path is the easiest way.

I'm considering proposing a change upstream to https://github.com/asdf-vm/actions to make a better testing framework for plugin behaviour, but that seems like a lot of work, so this will do for now.

### CODE REVIEW

**Comment by kennyp** [comment]
@whi-tw the tests are great, thanks! We should definitely get those merged.

The behavior when parsing `go.mod` is actually taken from the the Go specification as mentioned in the [README](https://github.com/kennyp/asdf-golang#version-selection), so we probably shouldn't change that part.

Do you mind pulling that part out of the `parse-legacy-file` and we can merge the tests?

**Comment by whi-tw** [comment]
@kennyp Done - stripped out the version parsing logic, and reimplemented the tests for the new version logic (thank you for fixing that btw - I found it yesterday, while working out why my machine ground to a halt every so often!)

**Comment by kennyp** [comment]
@whi-tw Thanks! And yes, I agree it's brittle to make assumptions about the upstream directory layout. I'm hoping we can get something working on the issue I have open over there and have a supported solution.

**Comment by whi-tw** [comment]
@kennyp no clue how that flub ended up in the workflow, but should work now

**Review by kennyp — APPROVED** [review]

**Pull request merged**
